services:

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
        - PHP_TAG=${PHP_TAG}
    container_name: reversebox-php
    volumes:
      - ${HOME_MOUNT}:${HOME_MOUNT}
    working_dir: ${HOME_MOUNT}
    user: 1000:1000
    network_mode: host

  nodejs:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    container_name: reversebox-nodejs
    volumes:
      - ${HOME_MOUNT}:${HOME_MOUNT}
    working_dir: ${HOME_MOUNT}
    user: 1000:1000
    restart: unless-stopped
    command: tail -f /dev/null
    network_mode: host

  traefik:
    image: "traefik:latest"
    container_name: reversebox-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=proxy_network"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.local`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - proxynet

networks:
  proxynet:
    name: proxy_network
